name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ["bradsjm"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please provide as much detail as possible to help us investigate and fix the issue.

  - type: input
    id: version
    attributes:
      label: byte-blaster Version
      description: What version of byte-blaster are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.12.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen instead.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Import byteblaster
        2. Create client with options '...'
        3. Call method '...'
        4. See error
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: python
      placeholder: |
        import asyncio
        from byteblaster import ByteBlasterClient, ByteBlasterClientOptions

        async def main():
            options = ByteBlasterClientOptions(email="test@example.com")
            client = ByteBlasterClient(options)
            # Issue occurs here

        asyncio.run(main())

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: |
        Please provide any relevant error messages, stack traces, or log output.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      render: shell
      placeholder: |
        Paste error messages, stack traces, or log output here.

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any additional environment details that might be relevant
      placeholder: |
        - Installation method (pip, uv, etc.)
        - Virtual environment details
        - Network configuration
        - Server information (if connecting to ByteBlaster server)
        - Any other relevant system information

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        - Does this happen consistently or intermittently?
        - Any workarounds you've found?
        - Related issues or discussions?
        - Screenshots (if applicable)

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a minimal code sample that reproduces the issue
          required: true
        - label: I have included the complete error message/stack trace (if applicable)
          required: false
        - label: I have tested with the latest version of byte-blaster
          required: false
